name: blue_classic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  bluetooth_classic: ^0.0.2
  connectivity_plus: ^6.1.0
  wifi_iot: ^0.3.19+1
  http: ^1.2.2
  dart_ping: ^9.0.1
  network_info_plus: ^6.1.1
  rxdart: ^0.28.0
  provider: ^6.1.2
  url_launcher: ^6.3.1
  app_settings: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pivot-bme-full-eng.png
